### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by gomjellie** [pjc0247/new-home#2]
안녕하세요 준철님.

해당 프로젝트를 변형해서 GDG Devfest라는 행사에서 방탈출 게임 요소로 활요해서 사용하고 싶은데 혹시 가능할까요?

라이센스가 명시되어 있지 않아서 문의 드립니다!

**Comment by pjc0247** [comment]
안녕하세요

소스는 마음대로 쓰셔도 되며, 수정본을 공개 레포로 하실 필요도 없습니다.

다만 완성본이 나오시면 한번 보여주실 수 있을까요? (게임 용도로 쓰신다고 하여 호기심 떄문에 그렇습니다.)

**Comment by gomjellie** [comment]
물론이죠~ 감사합니다!

**Comment by gomjellie** [comment]
https://gomjellie-steganography.surge.sh 여기서 배포된 버전을 확인하실 수 있고, 아래처럼 게더타운과 연동해서 게더에서 탈출하는 형식으로 만들었습니다.

https://gather.town/app/J8BU6rhOCKhYivpi/GDSC-SSU

**Comment by pjc0247** [comment]
스테가노 그래피 오랜만에 보네요 ㅋㅋㅋ

공유해주셔서 감사합니다
